# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
    - libgmp-dev

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
- stack --no-terminal --install-ghc test

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

# Upload the resulting executable to S3
deploy:
  provider: s3
  access_key_id: AKIAJP7VW4B2IVAP5X4Q
  secret_access_key:
    secure: "L1l46CY75MDymhwiBAF5PFDgF18WLndwSneZksCk3pmyNd7UkmidTcfAoaar6uDtwkanyI74VcXENADkplbxFpMJkU1zjywItXpp5z2wPBQ0raGtKOIhLq6NJtxZAHHCdmcCPfPcKc5lgNKp+zcFL36iDTpYKgRkK5n231S0AEG4v0ZR7uQhriDVy1APLdyVYgLIaUM6q/yEiyaGolzlwCx3S9Q9/uEwwAmS59sPZ9Lnppm4jnDPsM87T31l7N2cgflck9YhsgLdO6642cWvRSDgNd3uzI66O0KRts0OAlOvKZSD1cVK/KUe2cGCxLhl5rY01W6uOCwBZ22ioI6OqD+Hd6sfHkAVEVZ9l+k8/0LRd6loG3JGCF47WaF4km0ZZF3qKWXBUf/seNt1i08aMWEXwGJ4U3CXVPaE9OHhdpZ2VwIiusSGxbQ9vAJDC8Me3LyYCQ2s5hUx84QclLY2bcQ+fJr6MtgGP0gLTO7aLmPsnXEDwCmePLce2+C8X4hfog78KMc30SWF3mWDklClKhbY8L2xXRrDNu3PLFIQmG5Ux4i0an7/Yg2ObhLR7AGuFu1SkP3UljMWSO7hf3B/XVZ9Y/SMmUXhwWc17ZVSN9vwaObzCmA/fZ+zbH3mP01EaVr8SzPrAZpowpZP3whYJXbrpZkMyNLg5VQySZmFEJY="
  bucket: haskellbr
  acl: public_read
  skip_cleanup: true
  local_dir: to-s3
  upload-dir: haskellbr.com
  on:
    repo: haskellbr/website
    branch: dev
