sudo: true

services:
  - docker

script:
- stack build
- stack test
- make docker

matrix:
  include:
  - env: GHCVER=7.10.2 STACKYAML=stack-7.10.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.2
        - libgmp-dev

install:
- stack --docker +RTS -N2 -RTS --no-terminal --skip-ghc-check setup

cache:
  directories:
  - ~/.stack
  apt: true
before_install:
- export PATH=/opt/ghc/$GHCVER/bin:$PATH
- export PATH=~/.local/bin:$PATH
- if [ ! -e ~/.local/bin/stack ]; then mkdir -p ~/.local/bin; travis_retry curl -L
  https://github.com/commercialhaskell/stack/releases/download/v0.1.2.0/stack-0.1.2.0-x86_64-linux.gz
  | gunzip > ~/.local/bin/stack; chmod a+x ~/.local/bin/stack; fi
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo
  '?')]"
- stack +RTS -N2 -RTS --version
language: c
