user-edited: true
stanzas:
  - type: webapp
    exec: ../dist/bin/haskellbr-website
    args: []
    hosts:
      - haskellbr-website.com
      - www.haskellbr-website.com
    requires-secure: false

  - type: static-files
    hosts:
      - haskellbr-website.com
    root: ../static

  - type: redirect
    hosts:
      - www.haskellbr-website.com
    actions:
      - host: haskellbr-website.com

# Use the following to automatically copy your bundle upon creation via `yesod
# keter`. Uses `scp` internally, so you can set it to a remote destination
copy-to: root@box:/opt/keter/incoming/

plugins:
  postgres: true
